# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raman
full_name: Ramaneswaran S
email: s.ramaneswaran2000@gmail.com
email2: ramanr@nvidia.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ramaneswaran.github.io/" # the base hostname & protocol for your site
github_username:  ramaneswaran
twitter_username: RamaneswaranS
linkedin_username: ramaneswaran
stackoverflow: 12242652/ramaneswaran
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
